set_property SRC_FILE_INFO {cfile:/home/shc/projects/vivado/air_soc/air_soc_coremark_vcu/air_soc.srcs/constrs_1/new/vcu108.xdc rfile:../../../air_soc.srcs/constrs_1/new/vcu108.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BC9  IOSTANDARD LVDS} [get_ports clk_p]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BC8  IOSTANDARD LVDS} [get_ports clk_n]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BC40 IOSTANDARD LVCMOS12} [get_ports {rst_ni}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BE24 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports uart_tx_o]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BC24 IOSTANDARD LVCMOS18} [get_ports uart_rx_i]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC P22 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {qspi_data_io[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N22 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {qspi_data_io[1]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC J20 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {qspi_data_io[2]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC K24 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {qspi_data_io[3]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC J24 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {qspi_cs_n_o}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC T23 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {qspi_sck_o}]
